name: cache-libs
description: Caches all libs from the current pipeline. Should help with build-times.

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16.17.2'
        cache: 'npm'
    # debug
    - run: ls -l dist/libs
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: cached-libs
        path: dist/libs/
        retention-days: 1
